sakara/sakara/common/urls.py
from django.conf.urls import patterns, include, url
import views
# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sakara.views.home', name='home'),
    # url(r'^sakara/', include('sakara.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
    url(r'^$', views.LoginView.as_view()),
    url(r'^login/$', views.LoginView.as_view()),
    url(r'^home/$', views.HomeView.as_view()),
    url(r'^client/$', views.ClientView.as_view()),
    url(r'^client/(?P<id>[0-9]+)/edit/$', views.AddClientView.as_view()),
    url(r'^client/add/$', views.AddClientView.as_view()),
    url(r'^catalogo/$', views.CatalogoView.as_view()),
)

sakara/sakara/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sakara.views.home', name='home'),
    # url(r'^sakara/', include('sakara.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('sakara.common.urls'))
)

sakara/sakara/common/models.py
from django.db import models


# Create your models here.
class Clientes(models.Model):
    nombres = models.CharField(max_length=50)
    apellidos = models.CharField(max_length=100)
    fecha_nac = models.DateField()
    direccion = models.CharField(max_length=100, blank=True)
    email = models.EmailField(blank=True)
    telefono = models.CharField(max_length=9, blank=True)
    movil = models.CharField(max_length=9, blank=True)
    fecha_alta = models.DateField()
    observaciones = models.CharField(max_length=200, blank=True)

    def _get_full_name(self):
        "Returns the person's full name."
        return u'%s %s' % (self.nombres, self.apellidos)
    full_name = property(_get_full_name)

    # def format_birthdate(self):
    #     return self.gecha_nac.strftime('%d/%Y')[:3] + "0's"
    # decade_born_in.short_description = 'Birth decade'

    def copy_model_instance(self, obj, id):
        for f in obj._meta.fields:
            self.__setattr__(f.name, getattr(obj, f.name))
        self.id = self.pk = id
        return self

class Productos(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200, blank=True)


class VentaProducto(models.Model):
    id_cliente = models.PositiveIntegerField()
    id_producto = models.PositiveIntegerField()
    fecha = models.DateField()
    cantidad = models.PositiveIntegerField()
    pago = models.FloatField()


class Servicios(models.Model):
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)


class Tipos(models.Model):
    id_servicio = models.PositiveIntegerField()
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)


class Subtipos(models.Model):
    id_tipo = models.PositiveIntegerField()
    nombre = models.CharField(max_length=50)
    descripcion = models.CharField(max_length=200)

class Consulta(models.Model):
    id_cliente = models.PositiveIntegerField()
    id_servicio = models.PositiveIntegerField()
    id_tipo = models.PositiveIntegerField()
    id_subtipo = models.PositiveIntegerField()
    fecha = models.DateField()
    pago = models.FloatField()
    tipo_pago = models.CharField(max_length=50)

sakara/sakara/common/views.py
# -*- coding: utf-8 -*-

from django.views.generic import TemplateView, View
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django import forms
from django.contrib import messages
from sakara.common.models import Clientes
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator
from sakara.jquery_validate import JqueryForm, JqueryModelForm
from sakara.common.constants import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.forms.models import model_to_dict

import datetime


class LoginForm(forms.Form):
    username = forms.CharField(
        label="Usuario",
        required=True,
        error_messages={
            "invalid": "Usuario invalido",
            "required": "El campo 'Usuario' es obligatorio"
        },
        widget=forms.TextInput(attrs={'placeholder': "Introduce nombre de usuario", 'autocomplete': 'off'})
    )

    password = forms.CharField(
        label="password",
        required=True,
        error_messages={
            "invalid": "Contraseña invalida",
            "required": "El campo 'contraseña' es obligatorio",
        },
        widget=forms.PasswordInput(attrs={'placeholder': 'Introduce la contraseña', 'autocomplete': 'off'})
    )


class ClientesForm(JqueryModelForm):
    def __init__(self, client=None, *args, **kwargs):
        self.base_fields['nombres'] = forms.CharField(
            label="nombres",
            max_length=50,
            initial=client["nombres"] if "nombres" in client and client["nombres"] else '',
            error_messages={
                'required': "Campo obligatorio.",
                'max_length': u"La longitud m\u00E1xima permitida es de 50 car\u00E1cteres.",
            },
            widget=forms.TextInput(attrs={'placeholder': 'Nombre'})
        )

        self.base_fields['apellidos'] = forms.CharField(
            label="apellidos",
            max_length=100,
            initial=client["apellidos"] if "apellidos" in client and client["apellidos"] else '',
            error_messages={
                'required': "Campo obligatorio.",
                'max_length': u"La longitud m\u00E1xima permitida es de 100 car\u00E1cteres."
            },
            widget=forms.TextInput(attrs={'placeholder': 'Apellidos'})
        )

        if "fecha_nac" in client and type(client["fecha_nac"]) is datetime.date:
            valid_datetime = datetime.datetime.strftime(client["fecha_nac"], '%d/%m/%Y')
        else:
            valid_datetime = client["fecha_nac"] if "fecha_nac" in client and client["fecha_nac"] else ''

        self.base_fields['fecha_nac'] = forms.DateField(
            label="fecha nacimiento",
            input_formats=['%d/%m/%Y'],
            help_text='Formato: %s/%s/%s' % (str(datetime.date.today().day).zfill(2),
                                             str(datetime.date.today().month).zfill(2),
                                             datetime.date.today().year),
            initial=valid_datetime,
            error_messages={
                'required': "Campo obligatorio",
                'invalid': u"El formato no es v\u00E1lido."
            },
            widget=forms.DateInput(attrs={'placeholder': 'Fecha de nacimiento', 'autocomplete': 'off'})
        )

        self.base_fields['direccion'] = forms.CharField(
            label="direccion",
            max_length=100,
            required=False,
            initial=client["direccion"] if "direccion" in client and client["direccion"] else '',
            error_messages={
                'max_length': u"La longitud m\u00E1xima permitida es de 100 car\u00E1cteres."
            },
            widget=forms.TextInput(attrs={'placeholder': 'Dirección'})
        )

        self.base_fields['email'] = forms.EmailField(
            label="email",
            required=False,
            initial=client["email"] if "email" in client and client["email"] else '',
            error_messages={
                'invalid': "Email invalido."
            },
            widget=forms.TextInput(attrs={'placeholder': 'Email'})
        )

        self.base_fields['telefono'] = forms.RegexField(
            label="telefono",
            required=False,
            max_length=9,
            regex=CONST_PHONENUMBER,
            initial=client["telefono"] if "telefono" in client and client["telefono"] else '',
            error_messages={
                'max_length': u"La longitud m\u00E1xima permitida es de 9 car\u00E1cteres.",
                'regex_pattern': u"El valor introducido no se corresponde a un tel\u00E9fono"
            },
            widget=forms.TextInput(attrs={'placeholder': 'Teléfono'})
        )

        self.base_fields['movil'] = forms.RegexField(
            label="movil",
            required=False,
            max_length=9,
            regex=CONST_PHONENUMBER,
            initial=client["movil"] if "movil" in client and client["movil"] else '',
            error_messages={
                'max_length': u"La longitud m\u00E1xima permitida es de 9 car\u00E1cteres.",
                'regex_pattern': u"El valor introducido no se corresponde a un tel\u00E9fono"
            },
            widget=forms.TextInput(attrs={'placeholder': 'Teléfono Móvil'})
        )

        if "fecha_alta" in client and type(client["fecha_alta"]) is datetime.date:
            valid_datetime = datetime.datetime.strftime(client["fecha_alta"], '%d/%m/%Y')
        else:
            valid_datetime = client["fecha_alta"] if "fecha_alta" in client and client["fecha_alta"] else ''

        self.base_fields['fecha_alta'] = forms.DateField(
            label="fecha alta",
            input_formats=['%d/%m/%Y'],
            help_text='Formato: %s/%s/%s' % (str(datetime.date.today().day).zfill(2),
                                             str(datetime.date.today().month).zfill(2),
                                             datetime.date.today().year),
            initial=valid_datetime,
            error_messages={
                'required': "Campo obligatorio",
                'invalid': u"El formato no es v\u00E1lido."
            },
            widget=forms.DateInput(attrs={'placeholder': 'Fecha de alta', 'autocomplete': 'off'})
        )

        self.base_fields['observaciones'] = forms.CharField(
            label="observaciones",
            max_length=200,
            required=False,
            initial=client["observaciones"] if "observaciones" in client and client["observaciones"] else '',
            error_messages={
                'max_length': u'La longitud m\u00E1xima permitida es de 200 car\u00E1cteres.'
            },
            widget=forms.Textarea(attrs={'placeholder': 'Observaciones', 'cols': 50, 'rows': 10})
        )
        super(ClientesForm, self).__init__(*args, **kwargs)

    class Meta:
        model = Clientes


class ClientesFilterForm(JqueryForm):

    fecha_inicio = forms.DateField(
        input_formats=['%d/%m/%Y'],
        label="fecha inicio",
        required=True,
        help_text='Formato: %s/%s/%s' % (str(datetime.date.today().day).zfill(2),
                                         str(datetime.date.today().month).zfill(2),
                                         datetime.date.today().year),
        error_messages={
            'invalid': u"El formato no es v\u00E1lido."
        },
        widget=forms.DateInput(attrs={'placeholder': 'Fecha de inicio', 'autocomplete': 'off'})
    )

    fecha_final = forms.DateField(
        input_formats=['%d/%m/%Y'],
        label="fecha final",
        required=True,
        help_text='Formato: %s/%s/%s' % (str(datetime.date.today().day).zfill(2),
                                         str(datetime.date.today().month).zfill(2),
                                         datetime.date.today().year),
        error_messages={
            'invalid': u"El formato no es v\u00E1lido."
        },
        widget=forms.DateInput(attrs={'placeholder': 'Fecha final', 'autocomplete': 'off'})
    )

    tipo_fecha = forms.ChoiceField(
        label="tipo de fecha",
        required=True,
        choices=CONST_SELECT_DATE,
        widget=forms.Select()
    )

    filter = forms.BooleanField(
        initial=False,
        required=False,
        widget=forms.HiddenInput()
    )


class LoginView(TemplateView):
    template_name = 'login.html'

    def get_context_data(self, **kwargs):
        context = super(LoginView, self).get_context_data(**kwargs)
        context["form"] = LoginForm()
        return context

    def post(self, request):
        v = {}
        form = v["form"] = LoginForm(data=request.POST)
        if form.is_valid():
            user = authenticate(username=form.cleaned_data["username"], password=form.cleaned_data["password"])
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect(CONST_URL_HOME)
                else:
                    messages.error(request, "Usuario no activo, contacta con el administrador.")
            else:
                messages.error(request, "Tu usuario/password es incorrecto")
        else:
            messages.error(request, 'Tu usuario/password es incorrecto')
        return self.render_to_response(v)


class ClientView(TemplateView):
    template_name = "client.html"

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(ClientView, self).dispatch(*args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super(ClientView, self).get_context_data(**kwargs)

        column = self.request.GET.get('column')
        orderby = "-" if self.request.GET.get('orderby') == "desc" else ""
        if column:
            c = Clientes.objects.all().order_by(orderby + column)
            context[column] = self.request.GET.get('orderby')

sakara/sakara/common/templates/add_client.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Añadir Cliente {% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function() {
            $( "#id_fecha_nac, #id_fecha_alta" ).datepicker({
                firstDay: 1,
                changeMonth: true,
                changeYear: true
            });
            $( "#id_fecha_nac, #id_fecha_alta" ).datepicker( $.datepicker.regional[ "es" ] );
        });
    </script>
    <header>
        <div class="row">
            <h2>Añadir cliente</h2>
        </div>
        {% load flash_messages %}{% print_flash_messages messages %}
    </header>
    <div id="tab1">
        {% load jquery_validate %}  {% validate form "cliente-form" %}
        <form id="cliente-form" method="post" action="/client/add/">{% csrf_token %}
            <div class="row">
                {{ form.nombres }}
                {% validate_server form "nombres" %}
            </div>
            <div class="row">
                {{ form.apellidos }}
                {% validate_server form "apellidos" %}
            </div>
            <div class="row">
                {{ form.fecha_nac }}
                {% validate_server form "fecha_nac" %}
                <div class="help_text">
                    {{ form.fecha_nac.help_text }}
                </div>
            </div>
            <div class="row">
                {{ form.direccion }}
                {% validate_server form "direccion" %}
            </div>
            <div class="row">
                {{ form.email }}
                {% validate_server form "email" %}
            </div>
            <div class="row">
                {{ form.telefono }}
                {% validate_server form "telefono" %}
            </div>
            <div class="row">
                {{ form.movil }}
                {% validate_server form "movil" %}
            </div>
            <div class="row">
                {{ form.fecha_alta }}
                {% validate_server form "fecha_alta" %}
                <div class="help_text">
                    {{ form.fecha_alta.help_text }}
                </div>
            </div>
            <div class="row">
                {{ form.observaciones }}
                {% validate_server form "observaciones" %}
            </div>
            <input id="submit"  type="submit" value="Añadir Cliente" />
        </form>
    </div>
{% endblock %}

sakara/sakara/common/templates/catalogo.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Catalogo {% endblock %}
{% block content %}
    <header>
        <div class="row">
            <h2>Sakara: Catalogo</h2>
        </div>
        {% load flash_messages %}{% print_flash_messages messages %}
    </header>
    <div id="tab1">
        <form id="servicios-form" method="post" action="/catalogo/">{% csrf_token %}
            <div class="row">
                {{ form.padre }}
            </div>
            <div class="row">
                {{ form.servicio }}
            </div>
            <div class="row">
                {{ form.descripcion }}
            </div>
            <button id="servicios-submit" name="servicios-submit" type="submit">
                <span>Añadir Servicio</span>
            </button>
        </form>
    </div>
{% endblock %}

sakara/sakara/common/templates/client.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Clientes {% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function() {
            $( "#id_fecha_inicio, #id_fecha_final" ).datepicker({
                firstDay: 1,
                changeMonth: true,
                changeYear: true
            });
            $( "#id_fecha_inicio, #id_fecha_final" ).datepicker( $.datepicker.regional[ "es" ] );
        });
    </script>
    <header>
        <div id="client_filter">
            {% load jquery_validate %}  {% validate form "clientef-filter-form" %}
            <form id="clientef-filter-form" method="get" action="/client/">
                <div class="row">
                    {{ form.fecha_inicio }}
                    {% validate_server form "fecha_inicio" %}
                    {{ form.fecha_final }}
                    {{ form.tipo_fecha }}
                    {{ form.filter }}
                    <input id="submit"  type="submit" value="Filtrar" />
                    <input id="clean"  type="submit" value="Limpiar" />
                </div>
            </form>
        </div>

    </header>
    <div id="pagination">
    {% if clients.object_list %}
        <table>
            <tr>
                <td class="nombres" onclick="pagination({{ clients.number }}, 'nombres', true)">Nombre<span class="{{ nombres }}"></span></td>
                <td class="apellidos" onclick="pagination({{ clients.number }}, 'apellidos', true)">Apellidos<span class="{{ apellidos }}"></span></td>
                <td class="fecha_nac" onclick="pagination({{ clients.number }}, 'fecha_nac', true)">Fecha nacimiento<span class="{{ fecha_nac }}"></span></td>
                <td class="fecha_alta" onclick="pagination({{ clients.number }}, 'fecha_alta', true)">Fecha de alta<span class="{{ fecha_alta }}"></span></td>
                <td>Dirección</td>
                <td>E-mail</td>
                <td>Teléfono</td>
                <td>Móvil</td>
                <td>Observaciones</td>
                <td></td>
            </tr>
            {% for contact in clients %}
                <tr>
                {# Each "contact" is a Contact model object. #}
                    <td>{{ contact.nombres }}</td>
                    <td>{{ contact.apellidos }}</td>
                    <td>{{ contact.fecha_nac|date:"d/m/Y" }}</td>
                    <td>{{ contact.fecha_alta|date:"d/m/Y" }}</td>
                    <td>{{ contact.direccion }}</td>
                    <td>{{ contact.email }}</td>
                    <td>{{ contact.telefono }}</td>
                    <td>{{ contact.movil }}</td>
                    <td>{{ contact.observaciones }}</td>
                    <td><a href="/client/{{ contact.id }}/edit">Editar</a></td>
                </tr>
            {% endfor %}
        </table>

        <div class="pagination">
            <span class="step-links">
                {% if clients.has_previous %}
                    <button type="button" onclick="pagination(1, '{{ column }}')">First</button>
                    <button type="button" onclick="pagination({{ clients.previous_page_number }}, '{{ column }}')">previous</button>
                {% endif %}
                <ul>
                    {% for item in clients.paginator.page_range %}
                        <li>
                            {% ifequal item clients.number %}
                                {{ item }}
                            {% else %}
                                <a href="javascript:void(0)" onclick="pagination({{ item }}, '{{ column }}')">{{ item }}</a>
                            {% endifequal %}
                        </li>
                    {% endfor %}
                </ul>
                {% if clients.has_next %}
                    <button type="button" onclick="pagination({{ clients.next_page_number }}, '{{ column }}')">next</button>
                    <button type="button" onclick="pagination({{ clients.paginator.num_pages }}, '{{ column }}')">Last</button>
                {% endif %}
            </span>
        </div>
    {% else %}
        <div>
        No se obtuvieron resultados
        </div>
    {% endif %}
    </div>
    <script type="text/javascript">
        {# index: actual postion in the paginator #}
        {# column: actual column to order #}
        {# table: true value if table column is clicked #}
        function pagination(index, column, table){
            var orderby = $("." + column + " span").attr('class');
            if (table){
                if (orderby == "desc"){
                    orderby = "asc";
                }else{
                    orderby = "desc";
                }
            }

            if($("#id_filter").val() == "true"){
                var send_data = {
                    "page": index,
                    "column": column,
                    "orderby": orderby,
                    "fecha_inicio": $("#id_fecha_inicio").val(),
                    "fecha_final": $("#id_fecha_final").val(),
                    "tipo_fecha": $("#id_tipo_fecha").val()
                };
            }else{
                $("#id_fecha_inicio").val("")
                $("#id_fecha_final").val("")
                $("#id_tipo_fecha").val("0")
                var send_data = {"page": index, "column": column, "orderby": orderby};
            }

            $.ajax({
                type : 'GET',
                url : '/client/',
                data : send_data,
                success: function(data)
                {
                    $("#pagination").html($(data).filter("#pagination").html());
                }
            });
        }

        $("#submit").click(function(e){
            if($("#clientef-filter-form").not(".status-error")){
                $.ajax({
                    type : 'GET',
                    url : '/client/',
                    data : {
                        "fecha_inicio": $("#id_fecha_inicio").val(),
                        "fecha_final": $("#id_fecha_final").val(),
                        "tipo_fecha": $("#id_tipo_fecha").val()
                    },
                    success: function(data)
                    {
                        $("#pagination").html($(data).filter("#pagination").html());
                        $("#id_filter").val("true");
                    }
                });
            }
            e.preventDefault();
        });

        $("#clean").click(function(e){
            e.preventDefault();
            if($("#clientef-filter-form .status-error")){
                $("#clientef-filter-form div").removeClass("status-error");
                $("#clientef-filter-form input").removeClass("error");
                $("#clientef-filter-form label").remove()
            }
            $("#id_filter").val("false");
            pagination(1, "nombres");

        });
    </script>
{% endblock %}

sakara/sakara/common/templates/client_form.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %}
    {% if params.id %}
        Editar Cliente
    {% else %}
        Añadir Cliente
    {% endif %}
{% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function() {
            $( "#id_fecha_nac, #id_fecha_alta" ).datepicker({
                firstDay: 1,
                changeMonth: true,
                changeYear: true
            });
            $( "#id_fecha_nac, #id_fecha_alta" ).datepicker( $.datepicker.regional[ "es" ] );
        });
    </script>
    <header>
        <div class="row">
            {% if params.id %}
                <h2>Editar cliente</h2>
            {% else %}
                <h2>Añadir cliente</h2>
            {% endif %}
        </div>
        {% load flash_messages %}{% print_flash_messages messages %}
    </header>
    <div id="tab1">
        {% load jquery_validate %}  {% validate form "cliente-form" %}
        {% if params.id %}
            <form id="cliente-form" method="post" action="/client/{{ params.id }}/edit/">
        {% else %}
            <form id="cliente-form" method="post" action="/client/add/">
        {% endif %}
            {% csrf_token %}
            <div class="row">
                {{ form.nombres }}
                {% validate_server form "nombres" %}
            </div>
            <div class="row">
                {{ form.apellidos }}
                {% validate_server form "apellidos" %}
            </div>
            <div class="row">
                {{ form.fecha_nac }}
                {% validate_server form "fecha_nac" %}
                <div class="help_text">
                    {{ form.fecha_nac.help_text }}
                </div>
            </div>
            <div class="row">
                {{ form.direccion }}
                {% validate_server form "direccion" %}
            </div>
            <div class="row">
                {{ form.email }}
                {% validate_server form "email" %}
            </div>
            <div class="row">
                {{ form.telefono }}
                {% validate_server form "telefono" %}
            </div>
            <div class="row">
                {{ form.movil }}
                {% validate_server form "movil" %}
            </div>
            <div class="row">
                {{ form.fecha_alta }}
                {% validate_server form "fecha_alta" %}
                <div class="help_text">
                    {{ form.fecha_alta.help_text }}
                </div>
            </div>
            <div class="row">
                {{ form.observaciones }}
                {% validate_server form "observaciones" %}
            </div>
            {% if params.id %}
                <input id="submit"  type="submit" value="Guardar" />
            {% else %}
                <input id="submit"  type="submit" value="Añadir" />
            {% endif %}
        </form>
    </div>
{% endblock %}

sakara/sakara/common/templates/consulta.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Consulta {% endblock %}
{% block content %}
    <script type="text/javascript">
        $(function() {
            $( "#id_fecha_nac" ).datepicker({
                firstDay: 1,
                changeMonth: true,
                changeYear: true
            });
            $( "#id_fecha_nac" ).datepicker( $.datepicker.regional[ "es" ] );
        });
    </script>
    <header>
        <div class="row">
            <h2>Sakara: Consulta</h2>
        </div>
        {% load flash_messages %}{% print_flash_messages messages %}
    </header>
    <div id="tab1">
        {% load jquery_validate %}  {% validate form "cliente-form" %}
        <form id="cliente-form" method="post" action="/consulta/">{% csrf_token %}
            <div class="row">
                {{ form.nombres }}
                {% validate_server form "nombres" %}
            </div>
            <div class="row">
                {{ form.apellidos }}
                {% validate_server form "apellidos" %}
            </div>
            <div class="row">
                {{ form.fecha_nac }}
                {% validate_server form "fecha_nac" %}
            </div>
            <div class="row">
                {{ form.direccion }}
                {% validate_server form "direccion" %}
            </div>
            <div class="row">
                {{ form.email }}
                {% validate_server form "email" %}
            </div>
            <div class="row">
                {{ form.observaciones }}
                {% validate_server form "observaciones" %}
            </div>
            <input id="submit"  type="submit" value="Añadir" />
        </form>
    </div>
{% endblock %}

sakara/sakara/common/templates/default.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
{% load static from staticfiles %}
    <head>
        <title>{% block page_title %} {% endblock %}</title>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
        <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
        <meta http-equiv="Pragma" content="no-cache" />
        <meta http-equiv="Expires" content="0" />
        <link rel="stylesheet" href='{% static "css/base.css" %}'/>
        <link rel="stylesheet" href='{% static "css/jquery-ui-1.9.2.custom.min.css" %}'/>
        <script src='{% static "js/jquery-1.8.3.js" %}' type="text/javascript" ></script>
        <script src='{% static "js/jquery-ui-1.9.2.custom.min.js" %}' type="text/javascript"></script>
        <script src='{% static "js/jquery.ui.datepicker-es.js" %}' type="text/javascript"></script>
    </head>
    <body>
        {% block content %} {% endblock %}
    </body>
</html>

sakara/sakara/common/templates/home.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Consulta {% endblock %}
{% block content %}
{% endblock %}

sakara/sakara/common/templates/login.html
{% extends "default.html" %}
{% load static from staticfiles %}
{% block page_title %} Login {% endblock %}
{% block content %}
    <header>
        <div class="row">
            <h2>Sakara: Login</h2>
        </div>
        {% load flash_messages %}{% print_flash_messages messages %}
    </header>
	<form id="login-form" method="post" action="/login/">{% csrf_token %}
        <div class="row">
            {{ form.username }}
        </div>
        <div class="row">
            {{ form.password }}
        </div>
		<input id="submit"  type="submit" value="Entrar" />
	</form>
{% endblock %}